apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: basic-app
  namespace: argocd
spec:
  destination:
    namespace: app-basic
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-basic
    repoURL: https://github.com/kbreit-insight/argocd-demos
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
